### ISSUE TITLE
Valore ACCEPT_FSL_EULA cancellato da script engicam-setup-environment

### ISSUE THREAD

**Issue by SCordibella** [engicam-stable/meta-engicam#1]
Se eseguo lo script engicam-setup-environment su una build già esistente in cui avevo accettato la licenza freescale ACCEPT_FSL_EULA = "1" lo script riporta che i file di configurazione non sono stati modificati, ma invece mi ritrovo il conf/local.conf con ACCEPT_FSL_EULA = "".

**Comment by engicam-stable** [comment]
Thank you for your message. 
Issue will be fixed in the next commit.
